% STOICAL - A Toolbox for Efficient Parameter and Structure Variation of Simulation Models in Simulink
% Copyright (C) 2015 Tilman Wippenbeck, Institute for High Voltage Technology, RWTH Aachen University
% 
% This file is part of STOICAL.
% 
% STOICAL is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% at your option any later version.
%
% STOICAL is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with this program.  If not, see <http://www.gnu.org/licenses/>. 

function [ list ] = commonSubsystemParameterList()
%COMMONSUBSYSTEMPARAMETERLIST Summary of this function goes here
%   Detailed explanation goes here

list = {...
'ActiveVariant'; ...
'ActiveVariantBlock'; ...
'AlgorithmParameters'; ...
'BlockChoice'; ...
'Blocks'; ...
'Capabilities'; ...
'CheckFcnCallInpInsideContextMsg'; ...
'CurrentBlock'; ...
'CurrentOutputPort'; ...
'DataTypeOverride_Compiled'; ...
'DeleteChildFcn'; ...
'ErrorFcn'; ...
'FunctionInterfaceSpec'; ...
'FunctionWithSeparateData'; ...
'GeneratePreprocessorConditionals'; ...
'HDLData'; ...
'InstantiateOnLoad'; ...
'IsSubsystemVirtual'; ...
'Lines'; ...
'Location'; ...
'Mask'; ...
'MaskCallbackString'; ...
'MaskCallbacks'; ...
'MaskDescription'; ...
'MaskDisplay'; ...
'MaskEnableString'; ...
'MaskEnables'; ...
'MaskHelp'; ...
'MaskIconFrame'; ...
'MaskIconOpaque'; ...
'MaskIconRotate'; ...
'MaskIconUnits'; ...
'MaskInitialization'; ...
'MaskNames'; ...
'MaskObject'; ...
'MaskPortRotate'; ...
'MaskPromptString'; ...
'MaskPrompts'; ...
'MaskPropertyNameString'; ...
'MaskRunInitForIconRedraw'; ...
'MaskSelfModifiable'; ...
'MaskStyleString'; ...
'MaskStyles'; ...
'MaskTabNameString'; ...
'MaskTabNames'; ...
'MaskToolTipString'; ...
'MaskToolTipsDisplay'; ...
'MaskTunableValueString'; ...
'MaskTunableValues'; ...
'MaskType'; ...
'MaskValueString'; ...
'MaskValues'; ...
'MaskVarAliasString'; ...
'MaskVarAliases'; ...
'MaskVariables'; ...
'MaskVisibilities'; ...
'MaskVisibilityString'; ...
'MaskWSVariables'; ...
'MemberBlocks'; ...
'MinAlgLoopOccurrences'; ...
'ModelBrowserVisibility'; ...
'ModelBrowserWidth'; ...
'Open'; ...
'OverrideUsingVariant'; ...
'PaperOrientation'; ...
'PaperPosition'; ...
'PaperPositionMode'; ...
'PaperSize'; ...
'PaperType'; ...
'PaperUnits'; ...
'Permissions'; ...
'PermitHierarchicalResolution'; ...
'PolySpaceEndComment'; ...
'PolySpaceStartComment'; ...
'PropExecContextOutsideSubsystem'; ...
'RTWFcnName'; ...
'RTWFcnNameOpts'; ...
'RTWFileName'; ...
'RTWFileNameOpts'; ...
'RTWMemSecDataConstants'; ...
'RTWMemSecDataInternal'; ...
'RTWMemSecDataParameters'; ...
'RTWMemSecFuncExecute'; ...
'RTWMemSecFuncInitTerm'; ...
'RTWSystemCode'; ...
'RTWdata'; ...
'ReportName'; ...
'RuntimeObject'; ...
'SCDBlockLinearizationSpecification'; ...
'SCDEnableBlockLinearizationSpecification'; ...
'ScreenColor'; ...
'ScrollbarOffset'; ...
'ShowPageBoundaries'; ...
'ShowPortLabels'; ...
'SystemSampleTime'; ...
'TemplateBlock'; ...
'TiledPageScale'; ...
'TiledPaperMargins'; ...
'TreatAsAtomicUnit'; ...
'Variant'; ...
'VariantControl'; ...
'ZoomFactor'; ...
'AncestorBlock'; ...
'AttributesFormatString'; ...
'BackgroundColor'; ...
'BlockDescription'; ...
'BlockDiagramType'; ...
'BlockType'; ...
'ClipboardFcn'; ...
'CloseFcn'; ...
'Commented'; ...
'CompiledPortComplexSignals'; ...
'CompiledPortDataTypes'; ...
'CompiledPortDesignMin'; ...
'CompiledPortDesignMax'; ...
'CompiledPortDimensions'; ...
'CompiledPortFrameData'; ...
'CompiledPortWidths'; ...
'CompiledSampleTime'; ...
'ContinueFcn'; ...
'CopyFcn'; ...
'DataTypeOverrideCompiled'; ...
'DeleteFcn'; ...
'DestroyFcn'; ...
'Description'; ...
'Diagnostics'; ...
'DialogParameters'; ...
'DropShadow'; ...
'ExtModeLoggingSupported'; ...
'ExtModeLoggingTrig'; ...
'ExtModeUploadOption'; ...
'FontAngle'; ...
'FontName'; ...
'FontSize'; ...
'FontWeight'; ...
'ForegroundColor'; ...
'Handle'; ...
'HiliteAncestors'; ...
'InitFcn'; ...
'InputSignalNames'; ...
'IntrinsicDialogParameters'; ...
'IOSignalStrings'; ...
'IOType'; ...
'LibraryVersion'; ...
'LineHandles'; ...
'LinkData'; ...
'LinkStatus'; ...
'LoadFcn'; ...
'MinMaxOverflowLogging_Compiled'; ...
'ModelCloseFcn'; ...
'ModelParamTableInfo'; ...
'MoveFcn'; ...
'Name'; ...
'NameChangeFcn'; ...
'NamePlacement'; ...
'ObjectParameters'; ...
'OpenFcn'; ...
'Orientation'; ...
'OutputSignalNames'; ...
'Parent'; ...
'ParentCloseFcn'; ...
'PauseFcn'; ...
'PortConnectivity'; ...
'PortHandles'; ...
'PortRotationType'; ...
'Ports'; ...
'Position'; ...
'PostSaveFcn'; ...
'PreCopyFcn'; ...
'PreDeleteFcn'; ...
'PreSaveFcn'; ...
'Priority'; ...
'ReferenceBlock'; ...
'RequirementInfo'; ...
'RTWData'; ...
'SampleTime'; ...
'Selected'; ...
'ShowName'; ...
'StartFcn'; ...
'StatePerturbationForJacobian'; ...
'StaticLinkStatus'; ...
'StopFcn'; ...
'Tag'; ...
'Type'; ...
'UndoDeleteFcn'; ...
'UserData'; ...
'UserDataPersistent' ...
};

end

