function [ path ] = project_paths()
folders = { ...
    'tests', ...
    fullfile('tests', 'models'), ...
    fullfile('doc', 'example', 'Example_1'), ...
    fullfile('doc', 'example', 'Example_1', 'model_per_step'), ...
    fullfile('doc', 'example', 'Example_2'), ...
    fullfile('doc', 'example', 'Example_2', 'model_per_step'), ...
    fullfile('doc', 'example', 'Example_3'), ...
    fullfile('doc', 'example', 'Example_3', 'model_per_step'), ...
    };

[projectRoot, ~, ~] = fileparts(mfilename('fullpath'));

path = projectRoot;
for ii = 1:length(folders)
    path = [path ';' fullfile(projectRoot, folders{ii})];
end

