
%stoical.prepare.label_definition.analyseExisting
stoical.prepare.label_definition.save
stoical.prepare.configure_simulink.setOutputSaveOptions
stoical.prepare.activate.Parameters
stoical.prepare.activate.Signals
stoical.prepare.activate.Variants
stoical.prepare.saveModelWithDefaultValues
%stoical.prepare.checkSuccessfulCompilationWithDefaultSettings;