%% used in example files
help getLabeledObjDataFromModelWorkspace
help getLogStatus
help setLogStatus
help setParameterValues2Default
help setParameterValue
help getActiveConfigurationAndParameters
help setBuildAndCacheFolder
help getSimulationIdentifier
help getSignalFromSimulinkOutputObj

%% workflow for creating STOICAL model
help analyse_ExistingLabelDefinitions
help save_LabelDefinitions

help configure_SimulinkOutputSaveOptions
help Parameters_PrepareModel
help Signals_PrepareModel
help Variants_PrepareModel

help SaveModelWithDefaultValues
help check_successfulCompilationWithDefaultSettings